---
name: CI
on:
  push:
    branches:
      - github*
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 0 * * *
jobs:
  ci:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        otp_vsn:
          - 'latest'
          # - '24.0'
          # - '23.3'
          # - '23.2'
          # - '23.1'
          # - '23'
          # - '22.3'
          # - '22.2'
          # - '22.1'
          # - '22'
          # - '21.3'
          # - '21.2'
          # - '21.1'
          # - '21'
          # - '20.3'
          # - '20.2'
          # - '20.1'
          # - '20'
          # - '19.3'
          # - '19.2'
          # - '19.1'
          # - '19'
    name: 'ci-erl:${{ matrix.otp_vsn }}'
    runs-on: ubuntu-latest
    container:
      image: 'erlang:${{ matrix.otp_vsn }}'
    steps:
      - shell: bash
        run: |
          apt-get update
          apt-get -y install tcl tcl-dev gettext
          cd /usr/src/
          wget https://github.com/git/git/archive/v2.18.0.tar.gz -O git.tar.gz
          tar -xf git.tar.gz
          cd git-*
          make prefix=/usr/local all
          make prefix=/usr/local install
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - shell: bash
        run: autoconf
      - shell: bash
        run: ./configure
      - shell: bash
        run: make
      - shell: bash
        run: make test
